import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/providers/trpc-provider";
import { UserStatusProvider } from "@/providers/user-status-provider";
import { Toaster } from "@/components/sonner";
import { UserProvider } from "@/providers/user-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <TRPCProvider>
          <UserProvider>
            <UserStatusProvider>{children}</UserStatusProvider>
          </UserProvider>
        </TRPCProvider>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
